services:
  api:
    image: minha-imagem-de-chat
    build: .
    command: node dist/index.js
    ports:
      - "3001:3001"
    restart: always  # Garante que o WebSocket/API sempre volte

  video-worker:
    image: minha-imagem-de-chat
    build: .
    command: node dist/worker.js
    restart: always  # Essencial para garantir processamento contínuo
    deploy:
      replicas: 30  # Escala para 50 workers
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.8'
          memory: 1G
