services:
  api:
    image: minha-imagem-de-chat
    build: .
    command: node dist/index.js
    ports:
      - "3001:3001"
    restart: always

  # Workers de 1 a 30
  worker1: &worker-base
    image: minha-imagem-de-chat
    build: .
    command: node dist/worker.js
    restart: always
    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '2'
          memory: 1G

  worker2: *worker-base
  worker3: *worker-base
  worker4: *worker-base
  worker5: *worker-base
  worker6: *worker-base
  worker7: *worker-base
  worker8: *worker-base
  worker9: *worker-base
  worker10: *worker-base
  worker11: *worker-base
  worker12: *worker-base
  worker13: *worker-base
  worker14: *worker-base
  worker15: *worker-base
  worker16: *worker-base
  worker17: *worker-base
  worker18: *worker-base
  worker19: *worker-base
  worker20: *worker-base
  worker21: *worker-base
  worker22: *worker-base
  worker23: *worker-base
  worker24: *worker-base
  worker25: *worker-base
  worker26: *worker-base
  worker27: *worker-base
  worker28: *worker-base
  worker29: *worker-base
  worker30: *worker-base